### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by thorly** [ruthamey/slipBERI#3]
How to get these three components（E, N, up component of LOS vector）？In my opinion，if only has one observed LOS displacement, we cannot get these three components.

**Comment by ruthamey** [comment]
Hi there, because you'll know the line of sight vector (or can calculate from azimuth and incidence angle) of the satellite that you're using you can resolve the line of sight vector into its three components, East, North and Up. 
e.g. in this example velocity is split into Vy and Vx: https://www.wolframalpha.com/input/?i=vector+component

This isn't resolving the _ground displacements_ into E, N, up - just the line of sight vector itself.

**Comment by thorly** [comment]
thank you
